Repository smogon/pokemon-showdown, pull requests merged in 2025-07, with the labels that each got.

#11198 Move the gender logic to the validator
  data/rulesets.ts
  sim/pokemon.ts
  sim/team-validator.ts
Labels: enhancement

#11203 Fix Klutz's interaction with Fling
  data/mods/gen4/moves.ts
  data/moves.ts
  sim/pokemon.ts
  test/sim/abilities/klutz.js
Labels: bug, mechanics: approved

#11259 SV NFE: Ban Vigoroth
  config/formats.ts
Labels: forum: approved

#11267 BDSP: Ban Chatot and Drifblim from PU
  data/mods/gen8bdsp/formats-data.ts
Labels: forum: approved

#11251 Don't update the timer when an updated request is sent
  server/room-battle.ts
  sim/side.ts
  test/sim/decisions.js
Labels: crashes /hotpatch

#11277 Gen 1: Ban all partial trapping moves from UU
  config/formats.ts
Labels: forum: approved

#11273 Don't freeze and thaw with Polar Flare in the same attack
  data/conditions.ts
  data/text/moves.ts
Labels: bug

#11208 Implement Imprison disabling logic using Test Fight
  data/moves.ts
  sim/battle.ts
  sim/pokemon.ts
  sim/side.ts
  test/sim/misc/dynamax.js
  test/sim/moves/imprison.js
Labels: bug, mechanics: approved

#11141 Add test for Gen 3 berries
  test/sim/items/sitrusberry.js
Labels: pastgens

#11297 Full Potential: Update bans 4
  config/formats.ts
Labels: forum: approved

#11300 ZU: Ban Porygon2
  data/formats-data.ts
Labels: forum: approved

#11304 Burn Up shouldn't thaw the user if it isn't a Fire type
  data/conditions.ts
  test/sim/moves/burnup.js
Labels: bug, mechanics: approved

#11146 Fix Healing Wish and Lunar Dance switch in priority in Gen 7
  data/mods/gen7/moves.ts
Labels: bug, pastgens, mechanics: approved

#11301 National Dex AAA: Ban Ceruledge
  config/formats.ts
Labels: forum: approved
