Repository smogon/pokemon-showdown, pull requests merged in 2025-05, with the labels that each got.

#11057 Improve error messages shown to non-autoconfirmed
  server/chat-plugins/friends.ts
  server/chat-plugins/teams.ts
  server/private-messages/index.ts
Labels: forum: approved

#10814 Fix: Terastallize Ogerpon and Terapagos with different Tera types
  data/abilities.ts
  data/cg-teams.ts
  data/mods/gen9dlc1/scripts.ts
  data/mods/mixandmega/scripts.ts
  data/pokedex.ts
  sim/battle-actions.ts
  sim/dex-species.ts
  sim/team-validator.ts
  test/sim/misc/ogerpon.js
  test/sim/misc/terapagos.js
Labels: mechanics: approved

#10890 Implement White Herb and Eject Pack like Mirror Herb
  data/items.ts
  test/sim/abilities/commander.js
  test/sim/items/ejectpack.js
  test/sim/items/whiteherb.js
Labels: mechanics: needs source

#10878 Refactor fainted forme regression
  data/abilities.ts
  data/conditions.ts
  data/mods/gen7/abilities.ts
  data/mods/gen7letsgo/scripts.ts
  data/mods/gen8/abilities.ts
  sim/battle.ts
  sim/pokemon.ts
  test/sim/misc/fainted-forme-regression.js
Labels: mechanics: approved

#11097 Add rule to automatically display Pokemon information
  config/formats.ts
  data/mods/ccapm2024/formats-data.ts
  data/mods/ccapm2024/pokedex.ts
  data/rulesets.ts
Labels: enhancement, othermetas

#10877 Fix Mold Breaker interactions with abilities' Start events
  data/abilities.ts
  data/mods/gen9ssb/abilities.ts
  sim/battle.ts
  test/sim/abilities/flowergift.js
Labels: bug

#11114 Gen 4: Fix Haze not removing Focus Energy
  data/mods/gen3/moves.ts
  data/mods/gen4/moves.ts
  test/sim/moves/haze.js
Labels: mechanics: approved

#10897 Fix Tera Blast's interaction with Unaware
  sim/pokemon.ts
  test/sim/abilities/download.js
  test/sim/moves/terablast.js
Labels: bug, mechanics: needs past gen

#10991 Fix Pursuit's interaction with Follow Me
  sim/pokemon.ts
  test/sim/moves/pursuit.js
Labels: bug, mechanics: approved

#11128 SSNDDOU: Ban Venusaur & Ally Switch
  config/formats.ts
Labels: forum: approved

#11145 Add test for Magician + Throat Spray
  test/sim/abilities/magician.js
Labels: mechanics: approved

#11140 Fix Chatter's old gen mechanics
  data/mods/gen4/abilities.ts
  data/mods/gen5/moves.ts
  test/sim/moves/chatter.js
Labels: bug, pastgens, mechanics: approved

#11139 Fix Echoed Voice's BP raise when there is no target
  data/moves.ts
  test/sim/moves/echoedvoice.js
Labels: bug, mechanics: approved

#11130 Activate Wonder Guard if the target is immune
  data/abilities.ts
  data/mods/fullpotential/scripts.ts
  data/mods/gen1/scripts.ts
  data/mods/gen1stadium/scripts.ts
  data/mods/gen2/scripts.ts
  data/mods/gen2stadium2/scripts.ts
  data/mods/gen3/scripts.ts
  data/mods/gen4/abilities.ts
  data/mods/gen9ssb/abilities.ts
  data/mods/passiveaggressive/abilities.ts
  data/mods/passiveaggressive/conditions.ts
  data/mods/passiveaggressive/items.ts
  data/mods/passiveaggressive/moves.ts
  data/mods/passiveaggressive/scripts.ts
  sim/battle-actions.ts
  sim/pokemon.ts
  test/sim/abilities/wonderguard.js
Labels: bug, mechanics: approved
