Repository smogon/pokemon-showdown, pull requests merged in 2025-06, with the labels that each got.

#11161 Implement genderless Pokemon in Hackmons
  sim/pokemon.ts
  test/sim/moves/wish.js
Labels: bug, hackmons

#11144 Fix Magic Bounce in Free-For-All battles
  data/abilities.ts
  data/mods/gen5/abilities.ts
  sim/battle.ts
  test/sim/abilities/magicbounce.js
Labels: bug, mechanics: approved

#11181 Add Acupressure to Evasion Moves Clause
  config/formats.ts
  data/rulesets.ts
Labels: forum: approved

#11184 Trademarked Update Bans + Unban Regigigas
  config/formats.ts
Labels: forum: approved

#11199 ADV: Move Medicham to OU
  data/mods/gen3/formats-data.ts
Labels: forum: approved

#11194 STABmons: Update bans
  config/formats.ts
Labels: forum: approved

#11207 Magnet Pull should pull allies in Gen 3
  data/mods/gen3/abilities.ts
  sim/dex-conditions.ts
  test/sim/abilities/magnetpull.js
Labels: bug, mechanics: approved

#11213 Fix HP bar percentages and colours
  config/formats.ts
  sim/pokemon.ts
Labels: bug

#11202 National Dex UU: Ban Hawlucha
  data/formats-data.ts
Labels: forum: approved

#11226 Ubers UU: Ban Spectrier
  config/formats.ts
Labels: forum: approved

#11221 ORAS ZU: Ban Huntail and Light Clay
  config/formats.ts
  data/mods/gen6/formats-data.ts
Labels: forum: approved
